"""Class number module — no SageMath dependency.

Loads precomputed h(O_K) from utils/data/class_numbers/ (generated by
generate_class_nr.py) and computes h(O_f) via the conductor formula.

Usage:
    from utils.class_nr import getClassNumber
    h = getClassNumber(D_K, f)
"""
import json
from pathlib import Path

_DATA_DIR = Path(__file__).parent / "data" / "class_numbers"
_BUCKET = 10_000
_cache: dict[int, dict[int, int]] = {}


def _bucket_path(idx: int) -> Path:
    lo = idx * _BUCKET + 1
    hi = (idx + 1) * _BUCKET
    return _DATA_DIR / f"class_numbers_{lo:05d}_{hi:05d}.json"


def _lookup(D: int) -> int:
    idx = (abs(D) - 1) // _BUCKET
    if idx not in _cache:
        with open(_bucket_path(idx)) as fh:
            raw = json.load(fh)
        _cache[idx] = {int(k): v for k, v in raw.items()}
    return _cache[idx][D]


def _kronecker(a: int, n: int) -> int:
    """Kronecker symbol (a/n), pure Python."""
    if n == 0:
        return 1 if abs(a) == 1 else 0
    result = 1
    if n < 0:
        n = -n
        if a < 0:
            result = -1
    while n % 2 == 0:
        n //= 2
        if a % 2 == 0:
            return 0
        if a % 8 in (3, 5):
            result = -result
    a %= n
    while a:
        while a % 2 == 0:
            a //= 2
            if n % 8 in (3, 5):
                result = -result
        if a % 4 == 3 and n % 4 == 3:
            result = -result
        a, n = n, a
        a %= n
    return result if n == 1 else 0


def _h_order(f: int, h_OK: int, D_K: int) -> int:
    if f == 1:
        return h_OK
    w = 3 if D_K == -3 else (2 if D_K == -4 else 1)
    result = f * h_OK
    n = f
    l = 2
    while l * l <= n:
        if n % l == 0:
            result = result * (l - _kronecker(D_K, l)) // l
            while n % l == 0:
                n //= l
        l += 1
    if n > 1:
        result = result * (n - _kronecker(D_K, n)) // n
    return result // w


def getClassNumber(t: int, f: int) -> int:
    """h(O_f): class number of the order of conductor f in Q(sqrt(t)).

    t  — fundamental imaginary discriminant D_K
    f  — conductor (positive integer)
    """
    return _h_order(f, _lookup(t), t)
